spring.application.name=ClienteMySQL
server.port=${PORT:8090}

spring.datasource.url=jdbc:${DATABASE_URL:mysql://localhost:3307/gestion_eventos}
spring.datasource.username=${MYSQLUSER:alumno}
spring.datasource.password=${MYSQLPASSWORD:alumno_pass}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymeleaf.cache=false